import React, { useState } from "react"
import { Search, Sparkles, ArrowRight, BarChart, Clock, Star, Users, FileText, Brain, Database, BookOpen, RefreshCw, GitCompare, Image, MessageSquare, ScanLine, PenTool, BarChart3, Bot, Mic, Menu, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { AppSidebar } from "@/components/AppSidebar"
import { ProfileDropdown } from "@/components/ProfileDropdown"
import { Link, useNavigate } from "react-router-dom"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"

// Import tool images
import itemGenerationImage from "@/assets/item-generation.png"
import itemWriterImage from "@/assets/item-writer.png"
import itemMetadataImage from "@/assets/item-metadata.png"
import courseGeneratorImage from "@/assets/course-generator.png"
import itemRewriterImage from "@/assets/item-rewriter.png"
import itemSimilarityImage from "@/assets/item-similarity.png"
import docChatImage from "@/assets/doc-chat-ncert.png"
import ocrImage from "@/assets/ocr.png"
import comingSoonImage from "@/assets/coming-soon.png"
import speechEvaluationImage from "@/assets/speech-evaluation-hero.jpg"
import essayEvaluationImage from "@/assets/essay-evaluation-hero.jpg"
import essayEvaluationZeroShotImage from "@/assets/essay-evaluation-zero-shot.jpg"

const Dashboard = () => {
  const navigate = useNavigate()
  const [activeTab, setActiveTab] = useState("All")
  const [subscriptionFilter, setSubscriptionFilter] = useState("All")
  const [hoveredTool, setHoveredTool] = useState<string | null>(null)
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 })
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [mobileSearchOpen, setMobileSearchOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState("")

  const tabs = [
    "All", "AI Generation", "Content Creation", "Education", 
    "Assessment", "Analytics", "AI Tools", "AI Interaction"
  ]

  const subscriptionCategories = ["All", "Active Subscriptions", "Yet to Subscribe"]

  const getIconForTool = (toolId: string) => {
    const iconMap = {
      "item-generation": Brain,
      "item-writer": PenTool,
      "item-metadata": Database,
      "course-generator": BookOpen,
      "item-rewriter": RefreshCw,
      "item-similarity": GitCompare,
      "course-generator-2": BookOpen,
      "scenario-and": FileText,
      "doc-chat-ncert": MessageSquare,
      "doc-chat-moby": MessageSquare,
      "ocr": ScanLine,
      "essay-evaluation": BarChart3,
      "essay-evaluation-zero": BarChart3,
      "test-forensics": BarChart,
      "image-generator": Image,
      "ai-persona": Bot,
      "speech-evaluation": Mic
    }
    return iconMap[toolId] || Sparkles
  }

  const aiTools = [
    {
      id: "item-generation",
      title: "Item Generation",
      description: "Subjective and objective questions are generated by the items th...",
      path: "/item-generation",
      image: itemGenerationImage,
      category: "AI Generation",
      badge: "New",
      badgeColor: "bg-blue-500",
      icon: Brain,
      subscriptionStatus: "active"
    },
    {
      id: "item-writer",
      title: "Item Writer",
      description: "Objective questions are generated by the items th...",
      path: "/item-writer",
      image: itemWriterImage,
      category: "Content Creation",
      icon: PenTool,
      subscriptionStatus: "active"
    },
    {
      id: "item-metadata",
      title: "Item Metadata",
      description: "AI powered tool knowledge generator helps you...",
      path: "/item-metadata",
      image: itemMetadataImage,
      category: "Analytics",
      icon: Database,
      subscriptionStatus: "pending"
    },
    {
      id: "course-generator",
      title: "Course Generator",
      description: "AI assistant course generator that will help yo...",
      path: "/course-generator",
      image: courseGeneratorImage,
      category: "Education",
      badge: "Popular",
      badgeColor: "bg-green-500",
      icon: BookOpen,
      subscriptionStatus: "active"
    },
    {
      id: "item-rewriter",
      title: "Item Rewriter",
      description: "Easily from old rewritten making the item better an...",
      path: "/item-rewriter",
      image: itemRewriterImage,
      category: "Content Creation",
      icon: RefreshCw,
      subscriptionStatus: "active"
    },
    {
      id: "item-similarity",
      title: "Item Similarity",
      description: "An AI powered tool helps compare questions and...",
      path: "/item-similarity",
      image: itemSimilarityImage,
      category: "Analytics",
      icon: GitCompare,
      subscriptionStatus: "pending"
    },
    {
      id: "course-generator-2",
      title: "Course Generator",
      description: "AI assistant course generator that will help yo...",
      path: "/course-generator-2",
      image: courseGeneratorImage,
      category: "Content Creation",
      badge: "Popular",
      badgeColor: "bg-green-500",
      icon: BookOpen,
      subscriptionStatus: "active"
    },
    {
      id: "scenario-and",
      title: "Scenario and...",
      description: "Generate a variety of scenario and various...",
      path: "/scenario",
      image: comingSoonImage,
      category: "Content Creation",
      icon: FileText,
      subscriptionStatus: "pending"
    },
    {
      id: "doc-chat-ncert",
      title: "Doc Chat - NCERT",
      description: "NCERT textbook by asking query, This textbo...",
      path: "/doc-chat-ncert",
      image: docChatImage,
      category: "Education",
      icon: MessageSquare,
      subscriptionStatus: "active"
    },
    {
      id: "doc-chat-moby",
      title: "Doc Chat - Moby-click",
      description: "Verify SAS textbook by asking query, This textbo...",
      path: "/doc-chat-moby",
      image: docChatImage,
      category: "Education",
      icon: MessageSquare,
      subscriptionStatus: "active"
    },
    {
      id: "ocr",
      title: "OCR",
      description: "Optical Character Recognition - Images from...",
      path: "/ocr",
      image: ocrImage,
      category: "AI Tools",
      badge: "New",
      badgeColor: "bg-blue-500",
      icon: ScanLine,
      subscriptionStatus: "active"
    },
    {
      id: "essay-evaluation",
      title: "Essay Evaluation - Fine tuned",
      description: "Subjective questions are evaluated for predefined books, using AI to get score and feedbacks for answer responses.",
      path: "/essay-evaluation",
      image: essayEvaluationImage,
      category: "Assessment",
      icon: BarChart3,
      subscriptionStatus: "pending"
    },
    {
      id: "essay-evaluation-zero",
      title: "Essay Evaluation - Zero Shot",
      description: "A paperless questions are evaluated using SBA and...",
      path: "/essay-evaluation-zero",
      image: essayEvaluationZeroShotImage,
      category: "Assessment",
      icon: BarChart3,
      subscriptionStatus: "pending"
    },
    {
      id: "test-forensics",
      title: "Test Forensics",
      description: "Find and leverage the power of analytics in online or...",
      path: "/test-forensics",
      image: comingSoonImage,
      category: "Analytics",
      icon: BarChart,
      subscriptionStatus: "pending"
    },
    {
      id: "image-generator",
      title: "Image Generator",
      description: "Stable Diffusion - AI image generator your thoughts...",
      path: "/image-generator",
      image: comingSoonImage,
      category: "AI Generation",
      badge: "Popular",
      badgeColor: "bg-green-500",
      icon: Image,
      subscriptionStatus: "active"
    },
    {
      id: "ai-persona",
      title: "AI Persona",
      description: "AI Persona for famous intellectual dialogues in...",
      path: "/ai-persona",
      image: comingSoonImage,
      category: "AI Interaction",
      icon: Bot,
      subscriptionStatus: "pending"
    },
    {
      id: "speech-evaluation",
      title: "Speech Evaluation",
      description: "AI-powered speech assessment tool for reading and speaking evaluation...",
      path: "/speech-evaluation",
      image: speechEvaluationImage,
      category: "Assessment",
      badge: "New",
      badgeColor: "bg-blue-500",
      icon: Mic,
      subscriptionStatus: "active"
    }
  ]

  const filteredTools = aiTools.filter(tool => {
    const matchesCategory = activeTab === "All" || tool.category === activeTab
    const matchesSubscription = 
      subscriptionFilter === "All" || 
      (subscriptionFilter === "Active Subscriptions" && tool.subscriptionStatus === "active") ||
      (subscriptionFilter === "Yet to Subscribe" && tool.subscriptionStatus === "pending")
    
    const matchesSearch = searchQuery.trim() === "" || 
      tool.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tool.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tool.category.toLowerCase().includes(searchQuery.toLowerCase())
    
    return matchesCategory && matchesSubscription && matchesSearch
  })

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Desktop Sidebar */}
      <div className="fixed left-0 top-0 h-full w-52 z-40 hidden lg:block">
        <AppSidebar />
      </div>

      {/* Mobile Menu Sheet */}
      <Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}>
        <SheetContent side="left" className="w-64 p-0">
          <AppSidebar onNavigate={() => setMobileMenuOpen(false)} />
        </SheetContent>
      </Sheet>

      {/* Mobile Search Sheet */}
      <Sheet open={mobileSearchOpen} onOpenChange={setMobileSearchOpen}>
        <SheetContent side="top" className="h-auto max-h-[80vh] flex flex-col">
          <div className="space-y-4 pt-6 flex-shrink-0">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">Search AI Tools</h2>
              {searchQuery && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setSearchQuery("")}
                  className="h-8 text-xs"
                >
                  Clear
                </Button>
              )}
            </div>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input 
                placeholder="Search by name, description, or category..." 
                className="pl-10 h-12 text-base"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                autoFocus
              />
            </div>
            {searchQuery && (
              <p className="text-sm text-muted-foreground">
                {filteredTools.length} {filteredTools.length === 1 ? 'result' : 'results'} found
              </p>
            )}
          </div>
          
          {/* Search Results Preview */}
          {searchQuery && (
            <div className="mt-4 flex-1 overflow-y-auto">
              {filteredTools.length > 0 ? (
                <div className="space-y-2">
                  {filteredTools.slice(0, 5).map((tool) => (
                    <div
                      key={tool.id}
                      onClick={() => {
                        setMobileSearchOpen(false)
                        navigate(tool.path)
                      }}
                      className="p-3 rounded-lg border bg-card hover:bg-accent cursor-pointer transition-colors"
                    >
                      <div className="flex items-start gap-3">
                        <div className="p-2 rounded-lg bg-primary/10 flex-shrink-0">
                          {React.createElement(getIconForTool(tool.id), {
                            className: "h-5 w-5 text-primary"
                          })}
                        </div>
                        <div className="flex-1 min-w-0">
                          <h3 className="font-medium text-sm mb-1">{tool.title}</h3>
                          <p className="text-xs text-muted-foreground line-clamp-2">
                            {tool.description}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                  {filteredTools.length > 5 && (
                    <p className="text-xs text-center text-muted-foreground py-2">
                      +{filteredTools.length - 5} more results
                    </p>
                  )}
                </div>
              ) : (
                <div className="text-center py-8">
                  <p className="text-muted-foreground">No tools found</p>
                  <p className="text-sm text-muted-foreground mt-1">Try a different search term</p>
                </div>
              )}
            </div>
          )}
        </SheetContent>
      </Sheet>
      
      <div className="ml-0 lg:ml-52 min-h-screen flex flex-col">
        {/* Header */}
        <header className="sticky top-0 z-50 bg-white border-b border-gray-200">
          <div className="flex h-16 items-center justify-between px-3 sm:px-6 gap-2 sm:gap-4">
            <div className="flex items-center gap-2 sm:gap-4 min-w-0 flex-1">
              {/* Mobile Menu Button */}
              <Button
                variant="ghost"
                size="icon"
                className="lg:hidden flex-shrink-0"
                onClick={() => setMobileMenuOpen(true)}
              >
                <Menu className="h-5 w-5" />
              </Button>
              <div className="min-w-0 flex items-center gap-3 flex-1">
                <h1 className="text-base sm:text-xl font-semibold text-gray-900 truncate">Welcome Back, Robert Jones!</h1>
              </div>
            </div>
            
            <div className="flex items-center gap-2 sm:gap-3 flex-shrink-0">
              <div className="hidden sm:flex items-center gap-2">
                <div className="w-4 h-4 bg-blue-600 rounded flex items-center justify-center">
                  <span className="text-white text-xs">✦</span>
                </div>
                <span className="text-xs sm:text-sm text-blue-600 font-medium whitespace-nowrap">4,651</span>
              </div>
              
              {/* Mobile Search Button */}
              <Button
                variant="ghost"
                size="icon"
                className="lg:hidden"
                onClick={() => setMobileSearchOpen(true)}
              >
                <Search className="h-5 w-5" />
              </Button>
              
              {/* Desktop Search */}
              <div className="relative hidden lg:block">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input 
                  placeholder="Search AI tools..." 
                  className="pl-10 pr-8 w-64 h-9"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery("")}
                    className="absolute right-2 top-1/2 transform -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  >
                    <X className="h-4 w-4" />
                  </button>
                )}
              </div>
              <ProfileDropdown />
            </div>
          </div>
        </header>

        {/* Page Title */}
        <div className="p-2">
          
          
        </div>

        {/* Subscription Filter */}
        <div className="px-6 pb-4">
          <div className="flex items-center gap-1 p-1 bg-gray-100 rounded-lg w-fit">
            {subscriptionCategories.map((category) => (
              <button
                key={category}
                onClick={() => setSubscriptionFilter(category)}
                className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${
                  subscriptionFilter === category
                    ? "bg-white text-blue-600 shadow-sm"
                    : "text-gray-600 hover:text-gray-900"
                }`}
              >
                {category}
              </button>
            ))}
          </div>
        </div>

        {/* Stats Cards */}
        <div className="px-3 sm:px-6 pb-4 sm:pb-6">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-2.5 sm:gap-6">
            <Card className="p-3 sm:p-6 bg-blue-50 border border-gray-200 shadow-sm">
              <div className="flex items-center gap-1.5 sm:gap-3 mb-2 sm:mb-4">
                <div className="w-6 h-6 sm:w-8 sm:h-8 bg-white rounded-lg flex items-center justify-center shadow-sm flex-shrink-0">
                  <Sparkles className="h-3 w-3 sm:h-4 sm:w-4 text-blue-600" />
                </div>
                <span className="font-medium text-xs sm:text-base text-gray-700 leading-tight">Available Tools</span>
              </div>
              <div className="text-lg sm:text-2xl font-bold text-gray-900 mb-0.5 sm:mb-1">16</div>
              <div className="text-[10px] sm:text-sm font-medium text-blue-600 leading-tight">AI-Powered</div>
            </Card>

            <Card className="p-3 sm:p-6 bg-green-50 border border-gray-200 shadow-sm">
              <div className="flex items-center gap-1.5 sm:gap-3 mb-2 sm:mb-4">
                <div className="w-6 h-6 sm:w-8 sm:h-8 bg-white rounded-lg flex items-center justify-center shadow-sm flex-shrink-0">
                  <Star className="h-3 w-3 sm:h-4 sm:w-4 text-green-600" />
                </div>
                <span className="font-medium text-xs sm:text-base text-gray-700 leading-tight">Active Access</span>
              </div>
              <div className="text-lg sm:text-2xl font-bold text-gray-900 mb-0.5 sm:mb-1">12</div>
              <div className="text-[10px] sm:text-sm font-medium text-green-600 leading-tight">Subscribed</div>
            </Card>

            <Card className="p-3 sm:p-6 bg-purple-50 border border-gray-200 shadow-sm">
              <div className="flex items-center gap-1.5 sm:gap-3 mb-2 sm:mb-4">
                <div className="w-6 h-6 sm:w-8 sm:h-8 bg-white rounded-lg flex items-center justify-center shadow-sm flex-shrink-0">
                  <ArrowRight className="h-3 w-3 sm:h-4 sm:w-4 text-purple-600" />
                </div>
                <span className="font-medium text-xs sm:text-base text-gray-700 leading-tight">Explore More</span>
              </div>
              <div className="text-lg sm:text-2xl font-bold text-gray-900 mb-0.5 sm:mb-1">4</div>
              <div className="text-[10px] sm:text-sm font-medium text-purple-600 leading-tight">Features</div>
            </Card>

            <Card className="p-3 sm:p-6 bg-orange-50 border border-gray-200 shadow-sm">
              <div className="flex items-center gap-1.5 sm:gap-3 mb-2 sm:mb-4">
                <div className="w-6 h-6 sm:w-8 sm:h-8 bg-white rounded-lg flex items-center justify-center shadow-sm flex-shrink-0">
                  <Clock className="h-3 w-3 sm:h-4 sm:w-4 text-orange-600" />
                </div>
                <span className="font-medium text-xs sm:text-base text-gray-700 leading-tight">Today's Usage</span>
              </div>
              <div className="text-lg sm:text-2xl font-bold text-gray-900 mb-0.5 sm:mb-1">847</div>
              <div className="text-[10px] sm:text-sm font-medium text-orange-600 leading-tight">Tokens</div>
            </Card>
          </div>
        </div>

        {/* Main Content */}
        <main className="flex-1 px-6 pb-6">

          {/* Filter Tabs */}
          <div className="flex gap-2 mb-6 overflow-x-auto">
            {tabs.map((tab) => (
              <Button
                key={tab}
                variant={activeTab === tab ? "default" : "outline"}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-2 rounded-lg whitespace-nowrap text-sm transition-all ${
                  activeTab === tab 
                    ? "bg-blue-600 hover:bg-blue-700 text-white shadow-sm" 
                    : "bg-background text-foreground border-input hover:bg-accent hover:text-accent-foreground hover:border-accent"
                }`}
              >
                {tab}
              </Button>
            ))}
          </div>

          {/* Search Results Info */}
          {searchQuery && (
            <div className="flex items-center justify-between mb-4">
              <p className="text-sm text-muted-foreground">
                Found {filteredTools.length} {filteredTools.length === 1 ? 'result' : 'results'} for "{searchQuery}"
              </p>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setSearchQuery("")}
              >
                Clear search
              </Button>
            </div>
          )}

          {/* AI Tools Grid */}
          {filteredTools.length > 0 ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {filteredTools.map((tool) => {
              const IconComponent = tool.icon
              return (
                <div 
                  key={tool.id}
                  className="relative"
                  onMouseEnter={() => setHoveredTool(tool.id)}
                  onMouseLeave={() => setHoveredTool(null)}
                  onMouseMove={(e) => {
                    const rect = e.currentTarget.getBoundingClientRect()
                    setMousePosition({
                      x: e.clientX - rect.left,
                      y: e.clientY - rect.top
                    })
                  }}
                >
                  <Card className="group bg-white border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200 hover:-translate-y-1">
                    <div className="relative">
                      <img 
                        src={tool.image} 
                        alt={tool.title}
                        className="w-full h-40 object-cover rounded-t-lg"
                      />
                      {/* Tool Icon Overlay */}
                      <div className="absolute top-3 left-3 w-8 h-8 bg-white/90 backdrop-blur-sm rounded-lg flex items-center justify-center shadow-sm">
                        <IconComponent className="h-4 w-4 text-gray-700" />
                      </div>
                      {tool.badge && (
                        <div className={`absolute top-3 right-3 px-2 py-1 rounded-md text-xs text-white font-medium ${tool.badgeColor} shadow-sm`}>
                          {tool.badge}
                        </div>
                      )}
                      <div className="absolute bottom-3 right-3 px-2 py-1 rounded-md text-xs font-medium text-gray-700 bg-white/90 backdrop-blur-sm shadow-sm">
                        {tool.category}
                      </div>
                    </div>
                    
                    <CardContent className="p-6">
                      <h3 className="font-semibold text-gray-900 mb-2 line-clamp-1">{tool.title}</h3>
                      <p className="text-sm text-gray-600 mb-4 line-clamp-2">{tool.description}</p>
                      
                      <Link to={tool.path}>
                        <Button 
                          className="w-full bg-blue-600 hover:bg-blue-700 text-white transition-all duration-200 hover:scale-[1.02]"
                          size="sm"
                        >
                          <Sparkles className="h-4 w-4 mr-2" />
                          Launch App
                        </Button>
                      </Link>
                    </CardContent>
                  </Card>
                  
                  {/* Custom cursor-following tooltip */}
                  {hoveredTool === tool.id && (
                    <div 
                      className="absolute z-50 pointer-events-none"
                      style={{
                        left: `${mousePosition.x + 15}px`,
                        top: `${mousePosition.y + 15}px`,
                      }}
                    >
                      <div className="bg-gray-900 text-white px-3 py-2 rounded-lg shadow-lg text-sm font-medium whitespace-nowrap">
                        {tool.title}
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
            </div>
          ) : (
            <div className="text-center py-16">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-muted mb-4">
                <Search className="h-8 w-8 text-muted-foreground" />
              </div>
              <h3 className="text-lg font-semibold mb-2">No tools found</h3>
              <p className="text-muted-foreground mb-4">
                We couldn't find any tools matching your search
              </p>
              <Button variant="outline" onClick={() => setSearchQuery("")}>
                Clear search
              </Button>
            </div>
          )}

          {/* Footer */}
          <footer className="mt-12 pt-8 border-t border-gray-200 text-center">
            <p className="text-sm text-gray-500">
              © 2025 Excelsoftt Technologies Ltd. All rights reserved. | 
              <span className="ml-2">Help Center</span> | 
              <span className="ml-2">Privacy Policy</span> | 
              <span className="ml-2">Terms of Service</span> | 
              <span className="ml-4">Version 1.0.0</span> | 
              <span className="ml-2 flex items-center gap-1">Powered by 
                <img 
                  src="/lovable-uploads/b5b0f5a8-9552-4635-8c44-d5e6f994179c.png" 
                  alt="AI-Levate" 
                  className="h-4 w-auto"
                />
              </span>
            </p>
          </footer>
        </main>
      </div>
    </div>
  )
}

export default Dashboard